#include $(srctree)/../$(MTK_TARGET_PROJECT_FOLDER)/eastaeon.mk
# Linux driver folder

ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/zet6221/
ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/zet6221/include/

ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/$(MTK_PLATFORM)/include/

obj-y	+=  zet6221.o

