include $(srctree)/drivers/misc/mediatek/Makefile.custom

# Linux driver folder
ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/zet6221/
ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/


obj-y	+=  zet6221.o

